const fs = require('fs');
let appContent = fs.readFileSync('src/App.tsx', 'utf8');

const oldTabsStr = `type Tab = 'pinterest' | 'youtube' | 'instagram' | 'tiktok' | 'facebook' | 'reddit' | 'x' | 'linkedin' | 'snapchat';

const TABS: { id: Tab; label: string; placeholder: string; name: string; description: string; title: string; keywords?: string }[] = [
  { id: 'pinterest', label: 'Pinterest', placeholder: 'Paste Pinterest Link Here', name: 'Pinterest Downloader', title: 'Aura Downloader - Download Pinterest Videos & Images Free', description: 'Best free Pinterest Downloader online. Download Pinterest videos, images, and GIFs in HD quality without watermark using Aura Downloader.', keywords: 'Aura Downloader, Pinterest downloader, download Pinterest video, Pinterest video downloader, Pinterest saver' },
  { id: 'youtube', label: 'YouTube', placeholder: 'Paste YouTube Link (Video, Short, Channel, Playlist)', name: 'YouTube Downloader', title: 'Aura Downloader - YouTube Downloader, Shorts & Reels Saver', description: 'Aura Downloader is the best free YouTube Downloader. Download YouTube videos, Shorts, and Reels in 1080p, 4K HD effortlessly.', keywords: 'Aura Downloader, YouTube downloader, YouTube Shorts downloader, YouTube Reel downloader, download YouTube video, YouTube to mp3' },
  { id: 'instagram', label: 'Instagram', placeholder: 'Paste Instagram Link Here', name: 'Instagram Downloader', title: 'Aura Downloader - Instagram Reels & Video Downloader', description: 'Free online Instagram Downloader by Aura Downloader. Download Instagram reels, photos, videos, IGTV, and stories in high quality easily.', keywords: 'Aura Downloader, Instagram downloader, download Instagram video, Instagram reels downloader, Instagram story saver' },
  { id: 'tiktok', label: 'TikTok', placeholder: 'Paste TikTok Link Here', name: 'TikTok Downloader', title: 'Aura Downloader - TikTok Downloader Without Watermark', description: 'Best free TikTok Downloader. Download TikTok videos without watermark in HD quality using Aura Downloader.', keywords: 'Aura Downloader, TikTok downloader, download TikTok video, TikTok no watermark, TikTok video downloader' },
  { id: 'facebook', label: 'Facebook', placeholder: 'Paste Facebook Link Here', name: 'Facebook Downloader', title: 'Aura Downloader - Download Facebook Videos & Reels Free', description: 'Free online Facebook Video Downloader by Aura Downloader. Download Facebook reels and videos in HD quality to your device fast and easily.', keywords: 'Aura Downloader, Facebook downloader, download Facebook video, Facebook reels downloader, FB video downloader' },
  { id: 'reddit', label: 'Reddit', placeholder: 'Paste Reddit Link Here', name: 'Reddit Downloader', title: 'Aura Downloader - Download Reddit Videos With Audio', description: 'Free Reddit Video Downloader. Download Reddit videos with sound in HD quality with Aura Downloader.', keywords: 'Aura Downloader, Reddit downloader, download Reddit video with audio, Reddit video saver' },
  { id: 'x', label: 'X (Twitter)', placeholder: 'Paste X / Twitter Link Here', name: 'X / Twitter Downloader', title: 'Aura Downloader - Download Twitter Videos & GIFs Free', description: 'Best free X (Twitter) Downloader. Download videos, GIFs, and media from tweets in HD quality quickly and securely with Aura Downloader.', keywords: 'Aura Downloader, Twitter downloader, X downloader, download Twitter video, save tweet video' },
  { id: 'linkedin', label: 'LinkedIn', placeholder: 'Paste LinkedIn Post Link Here', name: 'LinkedIn Downloader', title: 'Aura Downloader - Download LinkedIn Videos Free', description: 'Free online LinkedIn Video Downloader. Download LinkedIn videos, images, and documents in high quality directly to your device with Aura Downloader.', keywords: 'Aura Downloader, LinkedIn downloader, download LinkedIn video, LinkedIn video saver' },
  { id: 'snapchat', label: 'Snapchat', placeholder: 'Paste Snapchat Spotlight or Story Link', name: 'Snapchat Downloader', title: 'Aura Downloader - Download Snapchat Videos Free', description: 'Free online Snapchat Video Downloader. Download Snapchat Spotlight videos and stories in high quality directly to your device with Aura Downloader.', keywords: 'Aura Downloader, Snapchat downloader, download Snapchat video, Snapchat spotlight downloader, story saver' },
];`;

const newTabsStr = `type Tab = 'pinterest' | 'youtube' | 'instagram' | 'snapchat' | 'tiktok' | 'facebook' | 'reddit' | 'x' | 'linkedin';

const TABS: { id: Tab; label: string; placeholder: string; name: string; description: string; title: string; keywords?: string }[] = [
  { id: 'pinterest', label: 'Pinterest', placeholder: 'Paste Pinterest Link Here', name: 'Pinterest Downloader', title: 'Aura Downloader - Download Pinterest Videos & Images Free', description: 'Best free Pinterest Downloader online. Download Pinterest videos, images, and GIFs in HD quality without watermark using Aura Downloader.', keywords: 'Aura Downloader, Pinterest downloader, download Pinterest video, Pinterest video downloader, Pinterest saver' },
  { id: 'youtube', label: 'YouTube', placeholder: 'Paste YouTube Link (Video, Short, Channel, Playlist)', name: 'YouTube Downloader', title: 'Aura Downloader - YouTube Downloader, Shorts & Reels Saver', description: 'Aura Downloader is the best free YouTube Downloader. Download YouTube videos, Shorts, and Reels in 1080p, 4K HD effortlessly.', keywords: 'Aura Downloader, YouTube downloader, YouTube Shorts downloader, YouTube Reel downloader, download YouTube video, YouTube to mp3' },
  { id: 'instagram', label: 'Instagram', placeholder: 'Paste Instagram Link Here', name: 'Instagram Downloader', title: 'Aura Downloader - Instagram Reels & Video Downloader', description: 'Free online Instagram Downloader by Aura Downloader. Download Instagram reels, photos, videos, IGTV, and stories in high quality easily.', keywords: 'Aura Downloader, Instagram downloader, download Instagram video, Instagram reels downloader, Instagram story saver' },
  { id: 'snapchat', label: 'Snapchat', placeholder: 'Paste Snapchat Spotlight or Story Link', name: 'Snapchat Downloader', title: 'Aura Downloader - Download Snapchat Videos Free', description: 'Free online Snapchat Video Downloader. Download Snapchat Spotlight videos and stories in high quality directly to your device with Aura Downloader.', keywords: 'Aura Downloader, Snapchat downloader, download Snapchat video, Snapchat spotlight downloader, story saver' },
  { id: 'tiktok', label: 'TikTok', placeholder: 'Paste TikTok Link Here', name: 'TikTok Downloader', title: 'Aura Downloader - TikTok Downloader Without Watermark', description: 'Best free TikTok Downloader. Download TikTok videos without watermark in HD quality using Aura Downloader.', keywords: 'Aura Downloader, TikTok downloader, download TikTok video, TikTok no watermark, TikTok video downloader' },
  { id: 'facebook', label: 'Facebook', placeholder: 'Paste Facebook Link Here', name: 'Facebook Downloader', title: 'Aura Downloader - Download Facebook Videos & Reels Free', description: 'Free online Facebook Video Downloader by Aura Downloader. Download Facebook reels and videos in HD quality to your device fast and easily.', keywords: 'Aura Downloader, Facebook downloader, download Facebook video, Facebook reels downloader, FB video downloader' },
  { id: 'reddit', label: 'Reddit', placeholder: 'Paste Reddit Link Here', name: 'Reddit Downloader', title: 'Aura Downloader - Download Reddit Videos With Audio', description: 'Free Reddit Video Downloader. Download Reddit videos with sound in HD quality with Aura Downloader.', keywords: 'Aura Downloader, Reddit downloader, download Reddit video with audio, Reddit video saver' },
  { id: 'x', label: 'X (Twitter)', placeholder: 'Paste X / Twitter Link Here', name: 'X / Twitter Downloader', title: 'Aura Downloader - Download Twitter Videos & GIFs Free', description: 'Best free X (Twitter) Downloader. Download videos, GIFs, and media from tweets in HD quality quickly and securely with Aura Downloader.', keywords: 'Aura Downloader, Twitter downloader, X downloader, download Twitter video, save tweet video' },
  { id: 'linkedin', label: 'LinkedIn', placeholder: 'Paste LinkedIn Post Link Here', name: 'LinkedIn Downloader', title: 'Aura Downloader - Download LinkedIn Videos Free', description: 'Free online LinkedIn Video Downloader. Download LinkedIn videos, images, and documents in high quality directly to your device with Aura Downloader.', keywords: 'Aura Downloader, LinkedIn downloader, download LinkedIn video, LinkedIn video saver' },
];`;

if (appContent.includes(oldTabsStr)) {
  appContent = appContent.replace(oldTabsStr, newTabsStr);
  fs.writeFileSync('src/App.tsx', appContent);
  console.log("Patched order successfully.");
} else {
  console.log("Could not find the exact string.");
}
